# 
# login.http
#
# Sends the login request and saves the acces token as jwtoken
#
# @name login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

@jwtoken = {{login.response.body.token}}
